const legalEBCards = [
  'Top Idol, Pacifica', // EB 2 starts
  'Top Idol, Riviere',
  'Bermuda Princess, Lena',
  'Pearl Sisters, Perle',
  'Pearl Sisters, Perla',
  "Girls' Rock, Rio",
  'Mermaid Idol, Elly',
  'Super Idol, Ceram',
  'Top Idol, Flores',
  'Top Idol, Aqua',
  'Super Idol, Riviere',
  'Mermaid Idol, Flute',
  'Turquoise Blue, Tyrrhenia',
  'Bermuda Triangle Cadet, Weddell',
  'Bermuda Triangle Cadet, Riviere',
  'Velvet Voice, Raindear',
  'Rainbow Light, Carine',
  'Intelli-idol, Melville',
  'Snow White of the Corals, Claire',
  'Diva of Clear Waters, Izumi',
  'Mermaid Idol, Sedna',
  'Prism on the Water, Myrtoa',
  'Mermaid Idol, Felucca',
  'Mermaid Idol, Riviere',
  'Navy Dolphin, Amur',
  'Blazer Idols',
  'Comical Rainie',
  'Cooking Caspi',
  'Sleeping Beauty, Mousse',
  'Drive Quartet, Ressac',
  'Drive Quartet, Flows',
  'Drive Quartet, Shuplu',
  'Drive Quartet, Bubblin',
  'Bermuda Triangle Cadet, Shizuku',
  'Bermuda Triangle Cadet, Caravel',
  'Demonic Lord, Dudley Emperor', // EB 3 starts
  'Spectral Duke Dragon',
  'Reckless Express',
  'Martial Arts Mutant, Master Beetle',
  'White Dragon Knight, Pendragon',
  'Origin Mage, Ildona',
  'Dragonic Lawkeeper',
  'Jelly Beans',
  'Dudley Daisy',
  'Bewitching Officer, Lady Butterfly',
  'Toxic Trooper',
  'Toxic Soldier',
  'Gigantech Destroyer',
  'Black Dragon Knight, Vortimer',
  'Black Dragon Whelp, Vortimer',
  'Dudley Douglass',
  'Fierce Leader, Zachary',
  'Field Driller',
  'Medical Manager',
  'Smart Leader, Dark Bringer',
  'Kungfu Kicker',
  'Iron Fist Mutant, Roly Poly',
  'Transmutated Thief, Steal Spider',
  'Machining Mosquito',
  'Pest Professor, Mad Fly',
  'Megacolony Battler C',
  'Awaking Dragonfly',
  'Flash Edge Valkyrie',
  'Scout of Darkness, Vortimer',
  'Blade Feather Valkyrie',
  'War-horse, Raging Storm',
  'Falcon Knight of the Azure',
  'Knight of Determination, Lamorak',
  'Knight of Fighting Spirit, Dordona',
  'Cross Shot, Garp',
  'Twin Shine Swordsman, Marhaus',
  'Dragonic Executioner',
  'Gyro Slinger',
  'Commander, Garry Gannon',
  'Eagle Knight of the Skies',
  'Miru Biru',
  'Dragon Armored Knight',
  'Grapeshot Wyvern',
  'Omniscience Madonna',
  'Onmyoji of the Moonlit Night',
  'Blue Scale Deer',
  'Petal Fairy',
]