const BT1 = [
  'King of Knights, Alfred',
  'Blaster Blade',
  'Barcgal',
  'Dragonic Overlord',
  'Embodiment of Victory, Aleph',
  'CEO Amaterasu',
  'Battle Sister, Cocoa',
  'Asura Kaiser',
  'Demon Slaying Knight, Lohengrin',
  'Solitary Knight, Gancelot',
  'Flash Shield, Iseult',
  'Future Knight, Llew',
  'Vortex Dragon',
  'Dragon Knight, Aleph',
  'Wyvern Guard, Barri',
  'Lizard Soldier, Conroe',
  'Maiden of Libra',
  'Battle Sister, Mocha',
  'Battle Sister, Chocolat',
  'Juggernaut Maximum',
  'Knight of Silence, Gallatin',
  'Dragon Knight, Nehalem',
  'Wyvern Strike, Tejas',
  'Embodiment of Spear, Tahr',
  'Oracle Guardian, Apollon',
  'Oracle Guardian, Wiseman',
  'Lozenge Magus',
  'Mr. Invincible',
  'Brutal Jack',
  'King of Sword',
  'Queen of Heart',
  'Battleraizer',
  'Tyrant, Deathrex',
  'Assault Dragon, Blightops',
  'Stealth Dragon, Voidmaster',
  'Demon Eater',
  'Monster Frank',
  'Commodore Blueblood',
  'Hell Spider',
  'Bloody Hercules',
  'Covenant Knight, Randolf',
  'Little Sage, Marron',
  'Lake Maiden, Lien',
  'Wingal',
  'Weapons Dealer, Govannon',
  'Flogal',
  'Yggdrasil Maiden, Elaine',
  'Embodiment of Armor, Bahr',
  'Dragon Monk, Gojo',
  'Wyvern Strike, Jarran',
  'Dragon Dancer, Monica',
  'Lizard Soldier, Ganlu',
  'Dragon Monk, Genjo',
  'Oracle Guardian, Gemini',
  'Weather Girl, Milk',
  'Oracle Guardian, Nike',
  'Dream Eater',
  'Miracle Kid',
  'Hungry Dumpty',
  'Tough Boy',
  "Screamin' and Dancin' Announcer, Shout",
  'Clay-doll Mechanic',
  'Shining Lady',
  'Lucky Girl',
  'Ring Girl, Clara',
  'Sonic Noa',
  'Ironclad Dragon, Shieldon',
  'Stealth Beast, Chigasumi',
  'Stealth Dragon, Dreadmaster',
  'Stealth Beast, Hagakure',
  'Blue Dust',
  'Nightmare Baby',
  'Rock the Wall',
  'Highspeed, Brakki',
  'Wonder Boy',
  'Redshoe, Milly',
  'Dandy Guy, Romario',
  'Guiding Zombie',
  'Karma Queen',
  'Madame Mirage',
]