const BT3 = [
  'Stil Vampir',
  'Demon World Marquis, Amon',
  'Nightmare Doll, Alice',
  'Ravenous Dragon, Gigarex',
  'Swordsman of the Explosive Flames, Palamedes',
  'Goddess of the Full Moon, Tsukuyomi',
  'Goddess of the Half Moon, Tsukuyomi',
  'Ultimate Lifeform, Cosmo Lord',
  'Edel Rose',
  'Gwynn the Ripper',
  'March Rabbit of Nightmareland',
  'Doreen the Thruster',
  'Dusk Illusionist, Robert',
  'Crimson Beast Tamer',
  'Mirror Demon',
  'Hades Hypnotist',
  'Archbird',
  'Knight of Godly Speed, Galahad',
  'Dual Axe Archdragon',
  'Super Dimensional Robo, Daiyusha',
  'Imprisoned Fallen Angel, Saraqael',
  'Werwolf Sieger',
  'Demon of Aspiration, Amon',
  'Alluring Succubus',
  'Vermillion Gatekeeper',
  'Barking Manticore',
  'Barking Cerberus',
  'Skull Juggler',
  'Midnight Bunny',
  'Turquoise Beast Tamer',
  'Hades Ringmaster',
  'Raging Dragon, Blastsaurus',
  'Ravenous Dragon, Megarex',
  'Savage Warrior',
  'Toypugal',
  'Drangal',
  'Oracle Guardian, Blue Eye',
  'Godhawk, Ichibyoshi',
  'Death Army Lady',
  'Death Army Guy',
  'Decadent Succubus',
  'Prisoner Beast',
  'Poet of Darkness, Amon',
  'Blitzritter',
  'Hades Puppet Master',
  'Cursed Doctor',
  'Dark Queen of Nightmareland',
  'Elephant Juggler',
  'Hungry Clown',
  'Dark Metal Bicorn',
  'Dynamite Juggler',
  'Spiral Master',
  'Candy Clown',
  'Rainbow Magician',
  'Vacuum Mammoth',
  'Savage Destroyer',
  'Raging Dragon, Sparksaurus',
  'Herbivorous Dragon, Brutosaurus',
  'Pack Dragon, Tinyrex',
  'Savage Shaman',
  'Black Cannon Tiger',
  'Knight of Tribulations, Galahad',
  'Gigantech Dozer',
  'Swordsman of the Blaze, Palamedes',
  'Knight of Quests, Galahad',
  'Borgal',
  'Alabaster Owl',
  'Secretary Angel',
  'Oracle Guardian, Red Eye',
  'Faithful Angel',
  'Goddess of the Crescent Moon, Tsukuyomi',
  'Battle Sister, Vanilla',
  'Victory Maker',
  'Flame Edge Dragon',
  'Dragon Dancer, Lourdes',
  'Blue Ray Dracokid',
  'Cannon Ball',
  'Masked Police, Grander',
  'Karenroid, Daisy',
  'Workerpod, Saturday',
  'Bloody Calf,',
  'Circle Magus',
]