const BT6 = [
  'Circular Saw, Kiriel',
  'Battle Cupid, Nociel',
  'Ice Prison Necromancer, Cocytus',
  'Incandescent Lion, Blond Ezel',
  'Player of the Holy Bow, Viviane',
  'Dragonic Kaiser Vermillion',
  'Desert Gunner, Shiden',
  'Beast Deity, Azure Dragon',
  'Cosmo Healer, Ergodiel',
  'Core Memory, Armaros',
  'Love Machine Gun, Nociel',
  'Pure Keeper, Requiel',
  'Deadly Swordmaster',
  'Death Seeker, Thanatos',
  'Knight of Fury, Agravain',
  'Sleygal Dagger',
  'Halo Shield, Mark',
  'Vajra Emperor, Indra',
  'Dragonic Deathscythe',
  'Wyvern Guard, Guld',
  'Mobile Hospital, Feather Palace',
  'Drill Bullet, Geniel',
  'The Phoenix, Calamity Flame',
  'Gattling Shot, Barbiel',
  'Fate Healer, Ergodiel',
  'Miracle Feather Nurse',
  'Master Swordsman, Nightstorm',
  'Skeleton Demon World Knight',
  'Deadly Spirit',
  'Three Star Chef, Pietro',
  'Deadly Nightmare',
  'Knight of Superior Skills, Beaumains',
  'Mage of Calamity, Tripp',
  'Player of the Holy Axe, Nimue',
  'Crimson Lion Cub, Kyrph',
  'Riot General, Gyras',
  'Thunderstorm Dragoon',
  'Demonic Dragon Berserker, Garuda',
  'Desert Gunner, Raien',
  'Photon Bomber Wyvern',
  'Lizard Soldier, Saishin',
  'Beast Deity, White Tiger',
  'Pulse Wave, Adriel',
  'Million Ray Pegasus',
  'Iron Heart, Mastema',
  'Holy Zone, Penemue',
  'Burst Shot, Bethnael',
  'Thousand Ray Pegasus',
  'Heavenly Injector',
  'Lancet Shooter',
  'Carrier of the Life Water',
  'Clutch Rifle Angel',
  'Lightning Charger',
  'Thermometer Angel',
  'Rocket Dash Unicorn',
  'Bouquet Toss Messenger',
  'Aurora Ribbon Pigeon',
  'Critical Hit Angel',
  'Happy Bell, Nociel',
  'Sunny Smile Angel',
  'God-eating Zombie Shark',
  'Stormride Ghost Ship',
  'Undead Pirate of the Frigid Night',
  'Sea Navigator, Silver',
  'Skeleton Colossus',
  'Child Frank',
  'John the Ghostie',
  'Ripple Banshee',
  'Dragon Spirit',
  'Undead Pirate of the Cursed Rifle',
  'Captain Nightkid',
  'Skeleton Assault Troops Captain',
  'Ghoul Cannonball',
  'Hook-wielding Zombie',
  'Doctor Rouge',
  'Hades Steersman',
  'Gigantech Crusher',
  'Holy Mage, Manawydan',
  'Gigantech Commander',
  'Sacred Guardian Beast, Elephas',
  'Providence Strategist',
  'Knight of Elegant Skills, Gareth',
  'Waving Owl',
  'Little Battler, Tron',
  'Little Fighter, Cron',
  'Greeting Drummer',
  'Flame of Victory',
  'Breakthrough Dragon',
  'Hex Cannon Wyvern',
  'Dragon Monk, Ensei',
  'Red River Dragoon',
  'Stealth Fighter',
  'Lizard Soldier, Yowsh',
  'Spark Kid Dragoon',
  'Dragon Dancer, Catharina',
  'Malevolent Djinn',
  'Moai the Great',
  'Beast Deity, Black Tortoise',
  'Marvelous Hani',
  'Almighty Reporter',
  'Beast Deity, Scarlet Bird',
  'Red Card Dealer',
  'Greed Shade',
  'Coongal',
  'Battle Flag Knight, Laudine',
  'Satellitefall Dragon',
  'Dreadcharge Dragon',
  'Brightlance Dragoon',
  'Rising Phoenix',
  'Turboraizer',
  'Muscle Hercules',
  'Kungfu Kid, Bolta',
  'Cup Bowler',
]