const legalTDCards = [
  'Crimson Butterfly, Brigitte', // TD 1
  'Knight of Conviction, Bors',
  'Solitary Knight, Gancelot',
  'Knight of Silence, Gallatin',
  'Blaster Blade',
  'Knight of the Harp, Tristan',
  'Covenant Knight, Randolf',
  'Little Sage, Marron',
  'Wingal',
  'Starlight Unicorn',
  'Knight of Rose, Morgana',
  'Stardust Trumpeter',
  'Bringer of Good Luck, Epona',
  'Yggdrasil Maiden, Elaine',
  'Weapons Dealer, Govannon',
  'Flogal',
  'Dragonic Overlord', // TD 2
  'Dragon Monk, Goku',
  'Demonic Dragon Berserker, Yaksha',
  'Dragon Knight, Nehalem',
  'Berserk Dragon',
  'Wyvern Strike, Tejas',
  'Embodiment of Armor, Bahr',
  'Dragon Monk, Gojo',
  'Flame of Hope, Aermo',
  'Demonic Dragon Madonna, Joka',
  'Wyvern Strike, Jarran',
  'Lizard Runner, Undeux',
  'Dragon Dancer, Monica',
  'Lizard Soldier, Ganlu',
  'Dragon Monk, Genjo',
  'Demonic Dragon Mage, Rakshasa',
  'Gold Rutile', // TD 3
  'Death Metal Droid',
  'Mr. Invincible',
  'King of Sword',
  'Super Electromagnetic Lifeform, Storm',
  'NGM Prototype',
  'Tough Boy',
  'Oasis Girl',
  "Screamin' and Dancin' Announcer, Shout",
  'Queen of Heart',
  'Battering Minotaur',
  'Shining Lady',
  'Cannon Ball',
  'Ring Girl, Clara',
  'Battleraizer',
  'Oracle Guardian, Apollon', // TD 4
  'Goddess of Flower Divination, Sakuya',
  'Meteor Break Wizard',
  'Oracle Guardian, Wiseman',
  'Security Guardian',
  'Sword Dancer Angel',
  'Oracle Guardian, Gemini',
  'Dark Cat',
  'Weather Girl, Milk',
  'Battle Sister, Maple',
  'Luck Bird',
  'Oracle Guardian, Nike',
  'Dream Eater',
  'Victory Maker',
  'Lozenge Magus',
  'Great Silver Wolf, Garmore', // TD 5
  'Sleygal Double Edge',
  'Battlefield Storm, Sagramore',
  'Knight of Superior Skills, Beaumains',
  'Sleygal Sword',
  'Sacred Guardian Beast, Nemean Lion',
  'Charging Chariot Knight',
  'Knight of Elegant Skills, Gareth',
  'Evil Slaying Swordsman, Haugan',
  'Precipice Whirlwind, Sagramore',
  'Charjgal',
  'Blessing Owl',
  'Silver Fang Witch',
  'Grassland Breeze, Sagramore',
  'Silent Punisher',
  'Weapons Dealer, Gwydion',
  'Fortune Bell',
  'Elixir Sommelier',
  'Thunder Break Dragon', // TD 6
  'Djinn of the Lightning Flash',
  'Plasmabite Dragon',
  'Thunderstorm Dragoon',
  'Shieldblade Dragoon',
  'Djinn of the Lightning Flare',
  'Brightjet Dragon',
  'Red River Dragoon',
  'Lizard Soldier, Riki',
  'Lightning of Hope, Helena',
  'Djinn of the Lightning Spark',
  'Dragon Dancer, RaiRai',
  'Wyvern Supply Unit',
  'Lizard Soldier, Sishin',
  'Yellow Gem Carbuncle',
  'Old Dragon Mage',
  'Zephyr Kid, Hayate',
  'Demonic Dragon Nymph, Seiobo'
]