module.exports.BT2 = [ 'Sky Diver', // 80 cards
  'Spirit Exceed',
  'Ruin Shade',
  'Soul Saver Dragon',
  'Blazing Flare Dragon',
  'Seal Dragon, Blockade',
  'Scarlet Witch, CoCo',
  'Lion Heat',
  'General Seifried',
  'Cheer Girl, Marilyn',
  'King of Demonic Seas, Basskirk',
  'Witch Doctor of the Abyss, Negromarl',
  'Captain Nightmist',
  'Gust Jinn',
  'Young Pegasus Knight',
  'Chain-attack Sutherland',
  'Silent Tom',
  'Magician Girl, Kirara',
  'Twin Blader',
  'Top Idol, Flores',
  'Unite Attacker',
  'Treasured, Black Panther',
  'Dudley Dan',
  'Mecha Trainer',
  'Dancing Cutlass',
  'Chappie the Ghostie',
  'Gigantech Charger',
  'Great Sage, Barron',
  'High Dog Breeder, Akane',
  'Pongal',
  'Blazing Core Dragon',
  'Demonic Dragon Mage, Kimnara',
  'Luck Bird',
  'Winged Dragon, Skyptero',
  'Dragon Egg',
  'Top Idol, Aqua',
  'Bermuda Triangle Cadet, Caravel',
  'Master Fraude',
  'Scientist Monkey Rue',
  'Geograph Giant',
  'Panzer Gale',
  'Devil Summoner',
  'Cyclone Blitz',
  'Spike Brothers Assault Squad',
  'Sonic Breaker',
  'Cheerful Lynx',
  'Cheer Girl, Tiara',
  'Silence Joker',
  'Skeleton Swordsman',
  'Samurai Spirit',
  'Evil Shade',
  'Knight Spirit',
  'Skeleton Lookout',
  'Rick the Ghostie',
  'Rough Seas Banshee',
  'Knight of Truth, Gordon',
  'Soul Guiding Elf',
  'Pixy Fife and Drum',
  'Margal',
  'Dragon Knight, Berger',
  'Iron Tail Dragon',
  'Follower, Reas',
  'Lizard Runner, Nafd',
  'Gattling Claw Dragon',
  'Security Guardian',
  'One Who Gazes at the Truth',
  'Emergency Alarmer',
  'Psychic Bird',
  'Chaos Dragon, Dinochaos',
  'Cannon Fire Dragon, Cannon Gear',
  'NGM Prototype',
  'Cray Soldier',
  'Three Minutes',
  'Red Lightning',
  'Blazer Idols',
  'Lady Bomb',
  'Phantom Black',
  'Megacolony Battler A',
  'Silver Wolf',
  'Intelli-mouse',
]