module.exports.BT4 = [ 'Phantom Blaster Dragon', // 82 cards
  'Darkness Maiden, Macha',
  'Skull Witch, Nemain',
  'Enigman Storm',
  'Evil Armor General, Giraffa',
  'Amber Dragon, Eclipse',
  'Heatnail Salamander',
  'Stern Blaukluger',
  'Dark Metal Dragon',
  'Gururubau',
  'Dark Shield, Mac Lir',
  'Enigman Wave',
  'Cosmo Beak',
  'Diamond Ace',
  'Commander Laurel',
  'Elite Mutant, Giraffa',
  'Paralyze Madonna',
  'Amber Dragon, Dusk',
  'Blaukluger',
  'Fang of Light, Garmore',
  'Silver Spear Demon, Gusion',
  'Dark Mage, Badhabh Caar',
  'Knight of Darkness, Rugos',
  'Blaster Dark',
  'Fullbau',
  'Enigman Rain',
  'Twin Order',
  'Platinum Ace',
  'Cosmo Roar',
  'Enigman Flow',
  'Death Warden Ant Lion',
  'Violent Vesper',
  'Water Gang',
  'Gloom Flyman',
  'Larva Mutant, Giraffa',
  'Lizard Soldier, Raopia',
  'Amber Dragon, Dawn',
  'Armored Fairy, Shubiela',
  'Blaujunger',
  'Beast Knight, Garmore',
  'Demon World Castle, DonnerSchlag',
  'Demon World Castle, Fatalita',
  'Black Sage, Charon',
  'Witch of Nostrum, Arianrhod',
  'Doranbau',
  'Blaster Javelin',
  'Zappbau',
  'Grim Reaper',
  'Abyss Freezer',
  'Darkside Trumpeter',
  'Abyss Healer',
  'Enigman Shine',
  'Enigroid Comrade',
  'Enigman Ripple',
  'Glory Maker',
  'Justice Cobalt',
  'Army Penguin',
  'Cosmo Fang',
  'Justice Rose',
  'Ironcutter Beetle',
  'Tail Joe',
  'Pupa Mutant, Giraffa',
  'Stealth Millipede',
  'Sharp Nail Scorpio',
  'Raider Mantis',
  'Sonic Cicada',
  'Medical Battler, Ranpli',
  'Garnet Dragon, Flash',
  'Lava Arm Dragon',
  'Amber Dragon, Daylight',
  'Red Gem Carbuncle',
  'Flame Seed Salamander',
  'Eisenkugel',
  'Dancing Wolf',
  'Blaupanzer',
  'Toolkit Boy',
  'Fighting Battleship, Prometheus',
  'Grapple Mania',
  'Snogal',
  'Brugal',
  'Cursed Lancer',
  'Megacolony Battler B',
]