const BT7 = [ 'School Hunter, Leo-pald', // 102 cards
  'Guardian of Truth, Lox',
  'Binoculus Tiger',
  'Silver Thorn Dragon Tamer, Luquier',
  'Dark Lord of Abyss',
  'Emerald Witch, LaLa',
  "White Hare in the Moon's Shadow, Pellinore",
  'Chief Nurse, Shamsiel',
  'School Dominator, Apt',
  'Lamp Camel',
  'Monoculus Tiger',
  'Cable Sheep',
  'Sword Magician, Sarah',
  'Fire Breeze, Carrie',
  'Peek-a-boo',
  'Magician of Quantum Mechanics',
  'Blade Wing Reijy',
  'Emblem Master',
  'Yellow Bolt',
  'Listener of Truth, Dindrane',
  'Pencil Hero, Hammsuke',
  'Dumbbell Kangaroo',
  'Magnet Crocodile',
  'Law Official, Lox',
  'Pencil Squire, Hammsuke',
  'Thermometer Giraffe',
  'Tank Mouse',
  'Flask Marmoset',
  'Midnight Invader',
  'Dancing Princess of the Night Sky',
  "Bull's Eye, Mia",
  'Purple Trapezist',
  'Evil Eye Basilisk',
  'Hades Carriage of the Witching Hour',
  'Free Traveler',
  'Courting Succubus',
  'Sky Witch, NaNa',
  'Battle Sister, Glace',
  'Little Witch, LuLu',
  'Photon Archer, Griflet',
  'Lop Ear Shooter',
  'Spring Breeze Messenger',
  'Calculator Hippo',
  'Schoolbag Sea Lion',
  'Red Pencil Rhino',
  'Pencil Knight, Hammsuke',
  'Globe Armadillo',
  'Explosion Scientist, Bunta',
  'Multimeter Giraffe',
  'Canvas Koala',
  'Thumbtack Fighter, Resanori',
  'Tick Tock Flamingo',
  'Bringer of Knowledge, Lox',
  'Element Glider',
  'Failure Scientist, Ponkichi',
  'Feather Penguin',
  'Hula Hoop Capybara',
  'Acorn Master',
  'Schoolyard Prodigy, Lox',
  'Triangle Cobra',
  'Fortune-bringing Cat',
  'Alarm Chicken',
  'Eraser Alpaca',
  'Dictionary Goat',
  'Ruler Chameleon',
  'Nightmare Doll, Amy',
  'Dreamy Fortress',
  'See-saw Game Loser',
  'Drawing Dread',
  'Jumping Glenn',
  'Dreamy Ammonite',
  'See-saw Game Winner',
  'Pinky Piggy',
  'Girl Who Crossed the Gap',
  'Innocent Magician',
  'Flyer Flyer',
  'Cracker Musician',
  'Popcorn Boy',
  'Poison Juggler',
  'Demon Chariot of the Witching Hour',
  'Beast in Hand',
  'Cyber Beast',
  'Demon Bike of the Witching Hour',
  'Beautiful Harpuia',
  'Mirage Maker',
  'Rune Weaver',
  'Greedy Hand',
  'Devil in Shadow',
  'Mad Hatter of Nightmareland',
  'Hungry Egg of Nightmareland',
  'Cheshire Cat of Nightmareland',
  'Dark Knight of Nightmareland',
  'Battle Sister, Souffle',
  'Oracle Guardian, Shisa',
  'Moonsault Swallow',
  'Battle Sister, Eclair',
  'Master of Pain',
  'Disciple of Pain',
  'Speeder Hound',
  'Doctroid Megalos',
  'Doctroid Micros',
  'Hope Child, Turiel',
]