const legalPromos = [ 'Wingal', // 31 cards
  'Scale Dragon of the Magma Cave',
  'Guardian of the Skies, Night Griffon',
  'Alfred Early',
  'Exile Dragon',
  'Knight of Endurance, Lucan',
  'Dragon Undead, Skull Dragon',
  'King Seahorse',
  'Holy Disaster Dragon',
  'Sword Emperor, Dragonic Valblade',
  'Knowledge Drunkard',
  'Knight of the Steel Blade, Caradoc',
  'Dragonic Vanisher',
  'Sphere Magus',
  'High Dog Breeder, Seiran',
  'Battle Sister, Omelet',
  'Blackmane Witch',
  'Flirtatious Succubus',
  'Cycling Actor',
  'Beaker Holstein',
  'Lion Mane Stallion',
  'Dragonic Waterfall',
  'Stamp Sea Otter',
  'The Dark Dictator',
  'Epitome of Knowledge, Silvest',
  'Knight Squire, Allen',
  'Wyvern Strike, Plajuri',
  'Triple Dark Armor',
  'Land Battle Support Type, Enigship',
  'No Life King, Death Anchor',
  'Dark Lord of Pale Moon',
]