const TD1 = [ 'Crimson Butterfly, Brigitte', // 16 cards
  'Knight of Conviction, Bors',
  'Solitary Knight, Gancelot',
  'Knight of Silence, Gallatin',
  'Blaster Blade',
  'Knight of the Harp, Tristan',
  'Covenant Knight, Randolf',
  'Little Sage, Marron',
  'Wingal',
  'Starlight Unicorn',
  'Knight of Rose, Morgana',
  'Stardust Trumpeter',
  'Bringer of Good Luck, Epona',
  'Yggdrasil Maiden, Elaine',
  'Weapons Dealer, Govannon',
  'Flogal',
]