module.exports.TD5 = [ 'Great Silver Wolf, Garmore', // 18 cards
  'Sleygal Double Edge',
  'Battlefield Storm, Sagramore',
  'Knight of Superior Skills, Beaumains',
  'Sleygal Sword',
  'Sacred Guardian Beast, Nemean Lion',
  'Charging Chariot Knight',
  'Knight of Elegant Skills, Gareth',
  'Evil Slaying Swordsman, Haugan',
  'Precipice Whirlwind, Sagramore',
  'Charjgal',
  'Blessing Owl',
  'Silver Fang Witch',
  'Grassland Breeze, Sagramore',
  'Silent Punisher',
  'Weapons Dealer, Gwydion',
  'Fortune Bell',
  'Elixir Sommelier',
]